### PR TITLE
ENH: Run ITK tests on CircleCI

### PR DESCRIPTION
**Pull request by thewtex**
Create a Docker image with the testing environment. This image can be built by
calling test/ci/build.sh. To test merging this repository into ITK,
re-building ITK, and running ITK's MetaIO tests, call test/ci/run.sh.

### CODE REVIEW

**Comment by jcfr** [comment]
:+1:

**Comment by thewtex** [comment]
CircleCI build / test result:

  https://open.cdash.org/buildSummary.php?buildid=4983117

**Comment by fbudin69500** [comment]
Can you explain why using CircleCI instead of/on top of TravisCI? Is it to take advantage of docker images?

**Comment by thewtex** [comment]
@fbudin69500 I was unaware of the merge into ITK and tests in TravisCI -- looks great! I assumed this was not available following the discussion in #30 and added the functionality there. However, it looks like Travis Linux builds are timing out inside ITK. Since we have CircleCI, I will try disabling timeout builds.

**Pull request merged**
