### PR TITLE
ENH: workaround underflow issue, specially on macOS

### PR DESCRIPTION
**Pull request by issakomi**
libc++ sets _fail_ bit on _istream_ if read _double_ value is less than `std::numeric_limits<double>::min()`

S. discussion https://github.com/InsightSoftwareConsortium/ITK/issues/2602

Feel free to re-create, modify or close this PR.

### CODE REVIEW

**Comment by issakomi** [comment]
Currently WIP, requires a little more time.

**Comment by thewtex** [comment]
@issakomi thanks for working on this!

**Comment by issakomi** [comment]
Run ITK tests with the change.
`100% tests passed, 0 tests failed out of 2706`

**Comment by issakomi** [comment]
```cpp
#include <iostream>
#include <sstream>

int main(int,char**)
{
  std::istringstream iss("6.95279e-310");
  //std::istringstream iss("2.2250738585072014e-308"); // double min
  //std::istringstream iss("jkfbjffj");
  //std::istringstream iss("1e-9999999999999999999");
  double n;
  iss >> n;
  std::cout << "fail=" << (iss.fail() ? "true" : "false") << std::endl;
  std::cout << "n=" << n << std::endl;
  return 0;
}
```

The side effect might be that in unlikely case of garbage, something like "jgkfgjkfk" instead of double string, this will go through and set to zero.  So it is decision of the owners to take PR or close.

**Pull request merged**
