### PR TITLE
Fix valgrind memory leaks

### PR DESCRIPTION
**Pull request by dzenanz**
Once integrated into ITK, it should address https://github.com/InsightSoftwareConsortium/ITK/issues/880.

### CODE REVIEW

**Comment by blowekamp** [comment]
Thanks for fixing this up! Were you able to run valgrind to verify you got them all?

This looks very tedious keeping track of when to delete things... did you consider use of `std::unique_pointer` ( with it's array specialization)?

**Comment by dzenanz** [comment]
I didn't run valgrind to verify, mostly because I don't have it set up. Also the duplication of these tests in ITK proper were passing, and I copied over the missing `delete`s.

MetaIO needs a good refactoring, aimed mostly at reducing the excessive amounts of duplicated code in it, and also to modernize it by taking advantage of C++11 (e.g. availability of `std::string`). I don't have time for that now, but if I ever decide to overhaul compression in MetaIO some level of refactoring will be a prerequisite.

Side note: no major changes to MetaIO compression are making it into ITKv5.0. Will will have to settle for approximately 4x-5x faster compression on zlib level 2, which is now the default.

**Comment by blowekamp** [comment]
Looks like there are some CI segfaults.

IMHO, the additional compression algorithms can be added at any time. The proper time to change the defaults is another thing.

**Comment by dzenanz** [comment]
CI segfaults are because circle CI is using ITKv4.13.2 to test MetaIO. See if you can help with #76 which tackles that.

**Pull request merged**
