### PR TITLE
Fixes various warnings

### PR DESCRIPTION
**Pull request by seanm**
Fixes various warnings

### CODE REVIEW

**Comment by thewtex** [comment]
:+1: Thanks for the contribution!

[LGTM](http://www.lgtm.in/i/O7zdcTY2q)

Built fine locally.

**Comment by seanm** [comment]
Thx. Who do I pester to get this into VTK?

**Comment by thewtex** [comment]
It will be in ITK, soon :-).

To get it into VTK, I would ping the lists and @demarle and @mathstuf

**Comment by thewtex** [comment]
PS. If you wanted to get it into ITK, we have a script,

  ./Modules/ThirdParty/MetaIO/src/UpdateMetaIOFromUpstream.sh

This makes it low-overhead to perform updates, and it allows any contributor perform the upgrade. I don't know if one exists in VTK yet -- if not, it is a good idea to create one ;-).

**Comment by demarle** [comment]
Thanks Matt! I look forward to stealing that script into VTK.

David E DeMarle
Kitware, Inc.
R&D Engineer
21 Corporate Drive
Clifton Park, NY 12065-8662
Phone: 518-881-4909

**Pull request merged**
