### PR TITLE
Used clang-tidy to convert various NULL and 0 to nullptr

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by dzenanz** [comment]
I guess you need to explicitly request C++11 in the CMake code for this to compile properly.

**Comment by dzenanz** [comment]
In src's [CMakeLists](https://github.com/Kitware/MetaIO/blob/master/src/CMakeLists.txt) C++11 enabling code should be added, in a similar way to [this](https://github.com/InsightSoftwareConsortium/ITK/blob/4cf99119f03510018d222bdb729ca3a97222224d/CMakeLists.txt#L38-L53).

**Comment by seanm** [comment]
OK, I don't know CMake at all, but I know how to copy-paste... :)

**Comment by dzenanz** [comment]
Can you rebase this PR? That should get it passing CI tests.

**Comment by seanm** [comment]
Things seem green now...

**Pull request merged**
