### PR TITLE
vtk: don't use the `WIN32` define

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
I'm importing this from VTK's commit to MetaIO [here](https://gitlab.kitware.com/vtk/vtk/commit/f53b8a1a593301ed0f5a205c37e20872bfeac8e2).

**Comment by mathstuf** [comment]
I don't have merge rights here. Could you please merge it @thewtex?

**Comment by mathstuf** [comment]
Thanks.

**Comment by jcfr** [comment]
👍

**Comment by thewtex** [comment]
@mathstuf Thanks for pushing the fix upstream. Your account should be set to merge for next time :-)

**Comment by mathstuf** [comment]
No problem; I'm working on getting the third party imports in VTK to be enforced by the robot, so future fixes should come here first too :) .

Thanks for the merge bit.

**Pull request merged**
